name: ${project}
services:
    ${image}: #this is the service name
        image: ${registry}${project}/${image}:${tag}
        container_name: ${image}-${PID}
        hostname: ${image} #optional
        environment:
          - PUID=${PUID:-1000}
          - PGID=${GUID:-1000}
          #- USER=${USERNAME} #not sure if this should be done?
          - TZ=Etc/UTC
        restart: unless-stopped
        #network: rogue-gateway_rogue-network
        build:
            context: ${CONTEXT:-$PWD}
        stdin_open: true
        init: true
        tty: true
        entrypoint: ${ENTRYPOINT}
        #command: ${CMD}
        volumes:
            - /:/host/root/
            - ${PWD}:/host/cwd/
            - ${PARENT?Parent directory not set}:/host/parent/
            - ${RAMDISK?Ramdisk not set}:/host/ramdisk/
            - ${HOME:-~}:/host/home/

 #       env_file:
 #           - /under/my
 #       working_dir: /tmp/roguesecrets
#networks:
#  rogue-gatway_rogue-network:
#    external: true
