name: ${project}
services:
    ${image}: #this is the service name
        image: ${registry}${project}/${image}:${tag}
        container_name: ${image}-${PID}
        hostname: ${image} #optional
        user: ${PUID:-1000}:${PGID:-1000}
        environment:
          - PUID=${PUID:-1000}
          - PGID=${PGID:-1000}
          #not sure if this should be done?
          - USER=${USERNAME}
          - TZ=Etc/UTC
        restart: unless-stopped
        #network: rogue-gateway_rogue-network
        build:
            context: ${CONTEXT:-$PWD}
        stdin_open: true
        init: true
        tty: true
        #this is for podman
        userns_mode: keep-id
        entrypoint: ${ENTRYPOINT}
        command: ${COMMAND}
        volumes:
            - /:/host/root:Z
            - ${PWD}:/host/workdir:Z
            - ${PARENT?Variable PARENT directory not set}:/host/parent:Z
            - ${RAMDISK?Variable RAMDISK not set}/${PID}/runtime/memory:/host/memory:Z
            - ${RAMDISK?Variable RAMDISK not set}/${PID}/runtime/session:/host/session:Z
            #### this is special!! for passwd and group file
            ####- ${RAMDISK?Variable RAMDISK not set}/${PID}/hostuser:/host/hostuser:Z
            - ${HOME:-~}:/host/home:Z
            #TODO? - ${RAMDISK?Variable RAMDISK not set}/${PID}/runtime:/host/secrets:Z
            #TODO? - - ${RAMDISK?Variable RAMDISK not set}/${PID}/runtime/config:/host/config:Z
            #TODO? - - ${RAMDISK?Variable RAMDISK not set}/${PID}/runtime/data:/host/data:Z
            - ${XDG_CONFIG_HOME?Variable XDG_CONFIG_HOME not set}:/host/config:Z
            - ${XDG_CACHE_HOME?Variable XDG_CACHE_HOME not set}:/host/cache:Z
            - ${XDG_DATA_HOME?Variable XDG_DATA_HOME not set}:/host/data:Z
            - ${XDG_STATE_HOME?Variable XDG_STATE_HOME not set}:/host/state:Z
            - ${XDG_RUNTIME_DIR?Variable XDG_RUNTIME_DIR not set}:/host/runtime:Z
            - ${RogueCLI_APP?Variable RogueCLI_APP not set}:/RogueCLI:Z
            
            ### maybe remove due to security?
            ###- ${RAMDISK?Variable RAMDISK not set}/${PID}/runtime:/RogueCLI/runtime:Z
            - ${RAMDISK?Variable RAMDISK not set}/shared:/RogueCLI/shared:Z
            
            #- ${RogueCLI_DATA?Variable RogueCLI_DATA not set}:/RogueCLI/runtime/data
            #- ${RogueCLI_SECRETS?Variable RogueCLI_SECRETS not set}:/RogueCLI/runtime/secrets
            #- ${RogueCLI_CONFIG?Variable RogueCLI_CONFIG not set}:/RogueCLI/runtime/config
            #- ${RogueCLI_CACHE?Variable RogueCLI_CACHE not set}:/RogueCLI/runtime/cache
                        
            #TODO XDG_DATA_DIRS
            #TODO XDG_CONFIG_DIRS

 #       env_file:
 #           - /under/my
 #       working_dir: /tmp/roguesecrets
#networks:
#  rogue-gatway_rogue-network:
#    external: true
