name: ${project}
services:
    ${image}: #this is the service name
        image: ${registry}${project}/${image}:${tag}
        container_name: ${image}-${PID}
        hostname: ${image} #optional
        user: ${PUID:-1000}:${GUID:-1000}
        environment:
          - PUID=${PUID:-1000}
          - PGID=${GUID:-1000}
          #- USER=${USERNAME} #not sure if this should be done?
          - TZ=Etc/UTC
        restart: unless-stopped
        #network: rogue-gateway_rogue-network
        build:
            context: ${CONTEXT:-$PWD}
        stdin_open: true
        init: true
        tty: true
        entrypoint: ${ENTRYPOINT}
        command: ${CMD}
        volumes:
            - /:/host/root:Z
            - ${PWD}:/host/cwd:Z
            - ${PARENT?Variable PARENT directory not set}:/host/parent:Z
            - ${RAMDISK?Variable RAMDISK not set}:/host/ramdisk:Z
            - ${HOME:-~}:/host/home:Z
            #TODO? - ${DIR_SECRETS}:/host/secrets:Z
            #TODO? - /host/config:Z
            #TODO? - /host/data:Z
            #TODO XDG_CONFIG_HOME
            #TODO XDG_CACHE_HOME
            #TODO XDG_DATA_HOME
            #TODO XDG_STATE_HOME
            #TODO XDG_RUNTIME_DIR
            #TODO XDG_DATA_DIRS
            #TODO XDG_CONFIG_DIRS

 #       env_file:
 #           - /under/my
 #       working_dir: /tmp/roguesecrets
#networks:
#  rogue-gatway_rogue-network:
#    external: true
