version: "3"
name: ${project}
services:
    ${image}:
        stdin_open: true
        init: true
        tty: true
        volumes:
            - /:/host/root/
            - ${PWD}:/host/cwd/
            - ${PARENT}:/host/parent/
            - /tmp/RogueCLI:/host/session/
            - ${HOME}:/host/home/

 #       env_file:
 #           - /under/my
        working_dir: /tmp/roguesecrets
        image: ${registry}${project}/${image}:${tag}
