version: "3"
name: ${project}
services:
    ${image}:
        build:
            context: ${CONTEXT:-$PWD}
        stdin_open: true
        init: true
        tty: true
        entrypoint: ${ENTRYPOINT}
        volumes:
            - /:/host/root/
            - ${PWD}:/host/cwd/
            - ${PARENT}:/host/parent/
            - /tmp/RogueCLI:/host/session/
            - ${HOME:-~}:/host/home/

 #       env_file:
 #           - /under/my
 #       working_dir: /tmp/roguesecrets
        image: ${registry}${project}/${image}:${tag}
