name: ${project}
services:
    ${image}:
        stdin_open: true
        init: true
        tty: true
        volumes:
            - ${PWD}:/tmp/roguesecrets
 #       env_file:
 #           - /under/my
        working_dir: /tmp/roguesecrets
        image: ${project}/${image}:${tag}
