#!/bin/bash
set -ex
script_name=$(basename "$0")
(return 0 2>/dev/null) && sourced=true || sourced=false
if ! $sourced; then
 script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 if [ -f ${script_dir}/env ];then
  source ${script_dir}/env
 fi
fi

function header () {
 echo -e "RogueSecrets[${script_name}]  $1"
}

make_all_executable () {
    dir=${1:-$PWD}
    pattern=${2:-*.sh}
    find $dir -type f -iname "$pattern" -exec chmod +x {} \;
}

git_pull () {
  git stash
  git pull
  git stash pop
  git submodule update --init --recursive --remote
}

docker_build () {
  local log; log="$(docker build . -t $project/$image:$tag $1)"
  if [ $? -ne 0 ]; then
    echo "Error building image = $project/$image:$tag" > /dev/stderr
    echo "$log" > /dev/stderr
  fi
}

if ! command -v docker &> /dev/null; then
    header "Docker not found. Installing"
    set -euo pipefail
    $script_dir/src/common/install-docker.sh
    set +euo pipefail
elif [ -x "$(command -v docker-compose)" ]; then
    header "docker-compose (v1) is installed."
    header " will attempt to use docker-compose but may have incompabitliby issues."
    header "to force docker compose (v2) install. Run ${script_dir}/src/common/install-docker.sh"
    d_compose=(docker-compose)
elif $(docker compose &>/dev/null) && [ $? -eq 0 ]; then
    header "docker compose (v2) is installed."
    d_compose=(docker compose)
else
    header "Docker not found. Installing"
    set -euo pipefail
    $script_dir/src/common/install-docker.sh
    set +euo pipefail
fi

#if first variable == --help then print readme.md
if [ "$1" == "--help" ]; then
	# if glow exists then use that
	if command -v glow &> /dev/null; then
		glow "$script_dir/README.md"
	else
		cat "$script_dir/README.md"
	fi
	exit 0
fi

inpath=$1
# if [[ $inpath == ~* ]]; then
# 	#inpath="${inpath/#\~/$HOME}"
# 	echo "unaccepted path"
# 	exit 1
# fi
# if [[ $inpath == /* ]]; then
# 	#inpath="${inpath/#\/}"
# 	echo "unaccepted path"
# 	exit 1
# fi

#https://medium.com/oracledevs/creating-an-oracle-cloud-infrastructure-cli-toolkit-docker-image-35be0ca71aa

if [ "$1" == "--" ]; then
  if [ "$2" == "reset" ]; then
    cd ..
    rm -rf RogueSecrets/
    docker rmi $(docker images --filter=reference="rogueos/*:*" -q) -f
    git clone https://github.com/ktsuttlemyre/RogueSecrets.git
    cd RogueSecrets/
    chmod +x ./index.sh ./reset.sh
    #./index.sh
  fi
fi

export DOCKER_DEFAULT_PLATFORM=linux/amd64

#if image not already here
#if [ -z "$(docker images -q $project/$image:$tag 2> /dev/null)" ]; then
#  docker_build
#else
#  #cache to rebuild image evey week hard rebuild every month
#  created_date="$(docker inspect -f '{{ .Created }}' $project/$image:$tag)"
#  created_week=$(date +'%V' -d +'%Y-%m-%dT%H:%M:%S' --date="$created_date")
#  created_month=$(date +'%m' -d +'%Y-%m-%dT%H:%M:%S' --date="$created_date")
#  current_week=$(date +'%V')
#  current_month=$(date +'%m')
#  if [ "$created_week" -ne "$current_week" ]; then
#    git_pull
#    [ "$created_month" -ne "$current_month" ] && cache='--no-cache'
#    docker_build $cache
#  fi
#fi

#remove . if path starts with .
inpath=${inpath#'./'}

path_array=$(echo "$inpath" | sed 's/\//\n/g')

#echo $path_array

#run_this_context=false
#[ ! -f is_docker ] && run_this_context=true

path="$script_dir"
full_path="$script_dir/$inpath"
parent_path=$(dirname "$full_path")
if [[ -d "$full_path" ]] || [[ ! -x "$full_path" ]]; then
    header "Error must provide an executable file"
    exit 1
fi

#if is_context isn't set then find the context to run this command
if [ -z "${IS_ROGUE_CONTEXT}" ]; then
	traverse="$full_path"
	#traverse backword looking for docker-compose.yaml or docker-compose.env for context
	docker_compose_yaml='./docker-compose.yaml'
	docker_compose_env='./docker-compose.env'
	while
		traverse=$(dirname "$traverse")
		echo "path currently $traverse"
		for file in $traverse/docker-compose.*; do
			if [[ $file == *.yaml ]]; then
			    docker_compose_yaml="$file"
			elif [[ $file == *.env ]]; then
			    docker_compose_env="$file"
			fi
		done
	    [ ! -z "$traverse" ] && [ "$traverse" != '/' ]
	do :; done

	export PARENT=$(dirname "$PWD")
	#custom image name
	set -a      # turn on automatic exporting
	source "$docker_compose_env"
	set +a      # turn off automatic exporting
	export ENTRYPOINT=/rogue

	#Run image
	#d_compose_args=(-f <( envsubst < "$docker_compose_yaml" ) --env-file <( env ))
	# up ${d_compose[@]} -f <( envsubst < "$docker_compose_yaml" ) --env-file <( env ) up --pull always --build
	#run
	${d_compose[@]} -f <(envsubst < "$docker_compose_yaml" ) --env-file <(env) pull
	#get workdir from image
	#WORKDIR=$(docker image inspect -f '{{.Config.WorkingDir}}' "${image}")
	${d_compose[@]} -f <(envsubst < "$docker_compose_yaml" ) --env-file <(env) run --env IS_ROGUE_CONTEXT=true --build roguesecrets "${@:2}"
	if ! [ -z "$is_service" ]; then
		${d_compose[@]} -f <(envsubst < "$docker_compose_yaml" ) down
	fi
	rogue_envvars="/tmp/RogueCLI/.env"
	if [ -f rogue_envvars ]; then
		header "Exporting secrets to current session"
		case "$(uname)" in
			LINUX) export $(grep -v '^#' $rogue_envvars | xargs -d 'n' ) ;;
			*) echo "Error exporing values from container"  ;;
		esac
		rm $rogue_envvars
	fi

	exit
fi


echo "$script_dir/$inpath"
while IFS= read -r path_e; do
    path="$path/$path_e"

    #check if path is a directory or file
    if [[ -d $path ]]; then
        #iterate all files in path that are hidden files and source them
        for file in $path/.*; do
            if [[ ! -f $file ]]; then
                continue
            fi
            #if file ends with .sh or .env
            if [[ $file == *.sh || $file == *.env ]]; then
                source $file
            else
                env $file
            fi
        done
    elif [[ -f $path ]]; then #if path variable is a file then exec it
	exec env $path "${@:2}" </dev/tty
	# if test ! -t 0; then
	#     #echo "Read from stdin"
	#     #currently doesnt work with decrypt
	#     exec env $path "${@:2}" < /dev/stdin # or < /proc/$$/fd/0 for stdin
	# else
	# 	exec env $path "${@:2}" < /dev/tty # or < /proc/$$/fd/0 for stdin
	# fi
	#if it fails then exit with the same error number as the previous command
	if [ $? -ne 0 ]; then
	exit $?
	fi
	break
    else
	header "Error unknown path type"
    fi
done <<<"$path_array"




