#!/bin/sh

set -ex
if apt --help; then
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "$@"
  apt-get clean
  rm -rf /var/lib/apt/lists/*
else if apk --help; then
  apk add --no-cache --clean-protected "$@"
else
  echo 'Could not find package system'
  exit 1
fi
exit 0
